const AS_HOUSE_TYPES = `(
                            id SERIAL PRIMARY KEY,
                            name VARCHAR(50) NOT NULL,
                            shortname VARCHAR(50),
                            description VARCHAR(250),
                            updatedate DATE NOT NULL,
                            startdate DATE NOT NULL,
                            enddate DATE NOT NULL,
                            isactive BOOLEAN NOT NULL
                        );`;
const AS_PARAM = `(          
                               ID BIGINT NOT NULL,
                             OBJECTID BIGINT NOT NULL,
                             CHANGEID BIGINT,
                             CHANGEIDEND BIGINT NOT NULL,
                             TYPEID INTEGER NOT NULL,
                             VALUE TEXT NOT NULL,
                             UPDATEDATE DATE NOT NULL,
                             STARTDATE DATE NOT NULL,
                             ENDDATE DATE NOT NULL,
                             PRIMARY KEY (ID, OBJECTID));`;

const tableCreationScripts: any = {
    AS_ADDR_OBJ: `(
                             id         BIGINT       NOT NULL PRIMARY KEY,
                             objectid   BIGINT       NOT NULL,
                             objectguid UUID         NOT NULL,
                             changeid   BIGINT       NOT NULL,
                             name       VARCHAR(250) NOT NULL,
                             typename   VARCHAR(50)  NOT NULL,
                             level      VARCHAR(10)  NOT NULL,
                             opertypeid INTEGER      NOT NULL,
                             previd     BIGINT,
                             nextid     BIGINT,
                             updatedate DATE         NOT NULL,
                             startdate  DATE         NOT NULL,
                             enddate    DATE         NOT NULL,
                             isactual   INTEGER      NOT NULL,
                             isactive   INTEGER      NOT NULL                             
                            );`,
    AS_ADDR_OBJ_PARAMS: AS_PARAM,
    AS_ADDR_OBJ_DIVISION: `(
                             ID       BIGINT NOT NULL PRIMARY KEY,
                             PARENTID BIGINT NOT NULL,
                             CHILDID  BIGINT NOT NULL,
                             CHANGEID BIGINT NOT NULL
                            );`,
    AS_ADDR_OBJ_TYPES: `(
                            ID INT NOT NULL,
                            LEVEL INT NOT NULL,
                            SHORTNAME VARCHAR(50) NOT NULL,
                            NAME VARCHAR(250) NOT NULL,
                            DESCRIPTION VARCHAR(250),
                            UPDATEDATE DATE NOT NULL,
                            STARTDATE DATE NOT NULL,
                            ENDDATE DATE NOT NULL,
                            ISACTIVE BOOLEAN NOT NULL
                        );`,
    AS_ADM_HIERARCHY: `(
                             ID BIGINT NOT NULL,
                             OBJECTID BIGINT NOT NULL,
                             PARENTOBJID BIGINT,
                             CHANGEID BIGINT NOT NULL,
                             REGIONCODE VARCHAR(10),
                             AREACODE VARCHAR(10),
                             CITYCODE VARCHAR(10),
                             PLACECODE VARCHAR(10),
                             PLANCODE VARCHAR(10),
                             STREETCODE VARCHAR(10),
                             PREVID BIGINT,
                             NEXTID BIGINT,
                             UPDATEDATE DATE NOT NULL,
                             STARTDATE DATE NOT NULL,
                             ENDDATE DATE NOT NULL,
                             ISACTIVE INT NOT NULL,
                             PATH VARCHAR(255) NOT NULL
                        );`,
    AS_APARTMENT_TYPES: `(
                             ID INTEGER NOT NULL,
                             NAME VARCHAR(50) NOT NULL,
                             SHORTNAME VARCHAR(50),
                             DESCRIPTION VARCHAR(250),
                             UPDATEDATE DATE NOT NULL,
                             STARTDATE DATE NOT NULL,
                             ENDDATE DATE NOT NULL,
                             ISACTIVE BOOLEAN NOT NULL
                        );`,
    AS_APARTMENTS: ` (
                            ID BIGINT NOT NULL,
                            OBJECTID BIGINT NOT NULL,
                            OBJECTGUID UUID NOT NULL,
                            CHANGEID BIGINT NOT NULL,
                            NUMBER VARCHAR(50) NOT NULL,
                            APARTTYPE SMALLINT NOT NULL,
                            OPERTYPEID SMALLINT NOT NULL,
                            PREVID BIGINT,
                            NEXTID BIGINT,
                            UPDATEDATE DATE NOT NULL,
                            STARTDATE DATE NOT NULL,
                            ENDDATE DATE NOT NULL,
                            ISACTUAL BOOLEAN NOT NULL,
                            ISACTIVE BOOLEAN NOT NULL
                    );`,
    AS_APARTMENTS_PARAMS: AS_PARAM,
    AS_CARPLACES: `(
                            id BIGINT NOT NULL,
                            objectid BIGINT NOT NULL,
                            objectguid UUID NOT NULL,
                            changeid BIGINT NOT NULL,
                            number TEXT NOT NULL,
                            opertypeid INTEGER NOT NULL CHECK (opertypeid >= 0 AND opertypeid <= 99),
                            previd BIGINT,
                            nextid BIGINT,
                            updatedate DATE NOT NULL,
                            startdate DATE NOT NULL,
                            enddate DATE NOT NULL,
                            isactual INTEGER NOT NULL CHECK (isactual IN (0, 1)),
                            isactive INTEGER NOT NULL CHECK (isactive IN (0, 1))
                        );`,
    AS_CARPLACES_PARAMS: AS_PARAM,
    AS_CHANGE_HISTORY: `(
                            changeid BIGINT NOT NULL,
                            objectid BIGINT NOT NULL,
                            adrobjectid VARCHAR(36) NOT NULL,
                            opertypeid INTEGER NOT NULL,
                            ndocid BIGINT,
                            changedate DATE NOT NULL
                        );`,
    AS_HOUSE_TYPES: AS_HOUSE_TYPES,
    AS_ADDHOUSE_TYPES: AS_HOUSE_TYPES,
    AS_HOUSES_PARAMS: AS_PARAM,
    AS_HOUSES: `(
                            id BIGINT PRIMARY KEY,
                            objectid BIGINT NOT NULL,
                            objectguid UUID NOT NULL,
                            changeid BIGINT NOT NULL,
                            housenum VARCHAR(50),
                            addnum1 VARCHAR(50),
                            addnum2 VARCHAR(50),
                            housetype INTEGER,
                            addtype1 INTEGER,
                            addtype2 INTEGER,
                            opertypeid INTEGER NOT NULL,
                            previd BIGINT,
                            nextid BIGINT,
                            updatedate DATE NOT NULL,
                            startdate DATE NOT NULL,
                            enddate DATE NOT NULL,
                            isactual INTEGER NOT NULL,
                            isactive INTEGER NOT NULL
                        );`,
    AS_MUN_HIERARCHY: ` (
                             id BIGINT NOT NULL,
                             objectid BIGINT NOT NULL,
                             parentobjid BIGINT,
                             changeid BIGINT NOT NULL,
                             oktmo VARCHAR(11),
                             previd BIGINT,
                             nextid BIGINT,
                             updatedate DATE NOT NULL,
                             startdate DATE NOT NULL,
                             enddate DATE NOT NULL,
                             isactive BOOLEAN NOT NULL,
                             path TEXT NOT NULL
                        );`,
    AS_NORMATIVE_DOCS: ` (
                             ID BIGINT NOT NULL,
                             NAME VARCHAR(8000) NOT NULL,
                             DATE DATE ,
                             NUMBER VARCHAR(150) NOT NULL,
                             TYPE INTEGER NOT NULL,
                             KIND INTEGER NOT NULL,
                             UPDATEDATE DATE NOT NULL,
                             ORGNAME VARCHAR(255),
                             REGNUM VARCHAR(100),
                             REGDATE DATE,
                             ACCDATE DATE,
                             COMMENT VARCHAR(8000)
                        );`,
    AS_NORMATIVE_DOCS_KINDS: `(
                              ID INTEGER NOT NULL,
                              NAME VARCHAR(500) NOT NULL
                              );`,
    AS_NORMATIVE_DOCS_TYPES: `(
                              id INTEGER NOT NULL,
                              name VARCHAR(500) NOT NULL,
                              startdate DATE NOT NULL,
                              enddate DATE NOT NULL,
                              PRIMARY KEY (id)
                            );`,
    AS_OBJECT_LEVELS: `(
                            level SMALLINT NOT NULL,
                            name VARCHAR(250) NOT NULL,
                            shortname VARCHAR(50),
                            updatedate DATE NOT NULL,
                            startdate DATE NOT NULL,
                            enddate DATE NOT NULL,
                            isactive BOOLEAN NOT NULL
                      );`,
    AS_OPERATION_TYPES: `(
                            id SERIAL PRIMARY KEY,
                            name VARCHAR(100) NOT NULL,
                            shortname VARCHAR(100),
                            description VARCHAR(250),
                            updatedate DATE NOT NULL,
                            startdate DATE NOT NULL,
                            enddate DATE NOT NULL,
                            isactive BOOLEAN NOT NULL
                         );`,
    AS_PARAM: AS_PARAM,
    AS_PARAM_TYPES: `(
                            id SERIAL PRIMARY KEY,
                            name VARCHAR(50) NOT NULL,
                            code VARCHAR(50) NOT NULL,
                            description VARCHAR(120),
                            update_date DATE NOT NULL,
                            start_date DATE NOT NULL,
                            end_date DATE NOT NULL,
                            is_active BOOLEAN NOT NULL
                            );`,
    AS_REESTR_OBJECTS: `(
                            OBJECTID BIGINT NOT NULL,
                            CREATEDATE DATE NOT NULL,
                            CHANGEID BIGINT NOT NULL,
                            LEVELID INTEGER NOT NULL,
                            UPDATEDATE DATE NOT NULL,
                            OBJECTGUID CHAR(36) NOT NULL,
                            ISACTIVE INTEGER NOT NULL CHECK (ISACTIVE IN (0, 1))
                        );`,
    AS_ROOM_TYPES: `(
                            id SERIAL PRIMARY KEY,
                            name VARCHAR(100) NOT NULL,
                            shortname VARCHAR(50),
                            description VARCHAR(250),
                            updatedate DATE NOT NULL,
                            startdate DATE NOT NULL,
                            enddate DATE NOT NULL,
                            isactive BOOLEAN NOT NULL
                    );`,
    AS_ROOMS: `(
                            ID BIGINT NOT NULL PRIMARY KEY,
                            OBJECTID BIGINT NOT NULL,
                            OBJECTGUID UUID NOT NULL,
                            CHANGEID BIGINT NOT NULL,
                            NUMBER VARCHAR(50) NOT NULL,
                            ROOMTYPE INTEGER NOT NULL CHECK (ROOMTYPE BETWEEN 0 AND 9),
                            OPERTYPEID INTEGER NOT NULL CHECK (OPERTYPEID BETWEEN 0 AND 99),
                            PREVID BIGINT,
                            NEXTID BIGINT,
                            UPDATEDATE DATE NOT NULL,
                            STARTDATE DATE NOT NULL,
                            ENDDATE DATE NOT NULL,
                            ISACTUAL BOOLEAN NOT NULL CHECK (isactual = TRUE),
                            ISACTIVE BOOLEAN NOT NULL CHECK (isactive = TRUE)
                    );`,
    AS_ROOMS_PARAMS: AS_PARAM,
    AS_STEADS: ` (
                            id SERIAL PRIMARY KEY,
                            objectid INTEGER NOT NULL,
                            objectguid UUID NOT NULL,
                            changeid INTEGER NOT NULL,
                            number VARCHAR(250) NOT NULL,
                            opertypeid CHAR(2) NOT NULL CHECK (opertypeid ~ '^[0-9]{1,2}$'),
                            previd INTEGER,
                            nextid INTEGER,
                            updatedate DATE NOT NULL,
                            startdate DATE NOT NULL,
                            enddate DATE NOT NULL,
                            isactual INTEGER NOT NULL CHECK (isactual IN (0, 1)), 
                            isactive INTEGER NOT NULL CHECK (isactive IN (0, 1))
                );`,
    AS_STEADS_PARAMS: AS_PARAM

};

export default tableCreationScripts;