FROM node:21-alpine3.18 as build-stage
WORKDIR /app
COPY ./package.json /app
COPY ./src /app/src
COPY ./index.ts /app
COPY ./tsconfig.json /app
COPY ./package-lock.json /app
COPY ./.env /app

RUN npm install

CMD npm run test
